# python judge_answers.py -m augmxnt/shisa-gamma-7b-v1
# python judge_answers.py -m augmxnt/shisa-7b-v1
# python judge_answers.py -m augmxnt/shisa-llama3-8b-v1
# python judge_answers.py -m augmxnt/shisa-yi1.5-9b-v1
# python judge_answers.py -m augmxnt/shisa-gemma-7b-v1
# python judge_answers.py -m meta-llama/Meta-Llama-3-8B-Instruct
# python judge_answers.py -m meta-llama/Meta-Llama-3-70B-Instruct
# python judge_answers.py -m kinokokoro/cyberagent-mistral-nemo-webnovels
# python judge_answers.py -m Deepreneur/blue-lizard
# python judge_answers.py -m cyberagent/Mistral-Nemo-Japanese-Instruct-2408
